language: php

matrix:
  include:
    - php: 7.1
      env: DEPENDENCIES=lowest
    - php: 7.1
      env: DEPENDENCIES=highest
    - php: 7.2
      env: DEPENDENCIES=lowest
    - php: 7.2
      env: DEPENDENCIES=highest

before_script:
  - composer self-update
  - if [ "${DEPENDENCIES}" = "lowest" ]; then composer update --prefer-lowest --prefer-dist --no-interaction --no-progress; fi;
  - if [ "${DEPENDENCIES}" = "highest" ]; then composer update --prefer-dist --no-interaction --no-progress; fi;

script:
  - bin/phing